/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'service' : IDL.Text,
  'created' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'created' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'review' : IDL.Text,
  'date' : Time,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'service' : IDL.Text,
    'created' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'created' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'review' : IDL.Text,
    'date' : Time,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };