/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'service' : string,
  'created' : Time,
  'name' : string,
  'email' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface ContactMessage {
  'created' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Testimonial {
  'review' : string,
  'date' : Time,
  'name' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addTestimonial' : ActorMethod<[string, bigint, string], string>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitContactForm' : ActorMethod<[string, string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];